### PR TITLE
updated product page

### PR DESCRIPTION
**Pull request by Dev1nxavier**
updated component ProductPage to receive selected product, populate fields with product details.

### CODE REVIEW

**Comment by Dev1nxavier** [comment]
Thanks Patricia! Please test to make sure it works on your end. Talk to you
later tonight.

**Comment by gpatricia223** [comment]
I merged and resolved conflicts to my branch.  But I'm not getting all the
functionality as expected.  I'll need some help during class time to figure
it out.

**Comment by Dev1nxavier** [comment]
What issues are you seeing?

**Comment by gpatricia223** [comment]
The search is logging stuff about tents but not working. Also the
categories are not opening to a new window.

**Comment by Dev1nxavier** [comment]
Works on my end so sounds like problems with the merge. We will review on
call today.

**Comment by gpatricia223** [comment]
Yes, my thoughts exactly

**Comment by Dev1nxavier** [comment]
Hi Patricia,

You were right, I did a fresh pull and found search stuff that didnt carry
over. I fixed and did a new pull request. If you have time before class,
great. otherwise, we can wait for tonight.

**Pull request merged**
